export const ScheduleConsts = {
  breakfast: {
    recipeId: '',
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
    eaten: false,
    time: '00:00',
  },
  secondBreakfast: {
    recipeId: '',
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
    eaten: false,
    time: '00:00',
  },
  lunch: {
    recipeId: '',
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
    eaten: false,
    time: '00:00',
  },
  tea: {
    recipeId: '',
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
    eaten: false,
    time: '00:00',
  },
  dinner: {
    recipeId: '',
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
    eaten: false,
    time: '00:00',
  },
  snacks: [],
};

export const ScheduleDetailsConsts = {
  totalCalories: 0,
  eatenCalories: 0,
  totalCarbohydrates: 0,
  eatenCarbohydrates: 0,
  totalProteins: 0,
  eatenProteins: 0,
  totalFats: 0,
  eatenFats: 0,
};
