export const ScheduleConsts = {
  breakfast: {
    recipeId: 0,
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
  },
  secondBreakfast: {
    recipeId: 0,
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
  },
  lunch: {
    recipeId: 0,
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
  },
  tea: {
    recipeId: 0,
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
  },
  dinner: {
    recipeId: 0,
    recipeName: '',
    recipeImage: '',
    calories: 0,
    fats: 0,
    proteins: 0,
    carbohydrates: 0,
  },
};
