export const UserConsts = {
  id: '',
  userImage: '',
  userName: '',
  email: '',
  age: 0,
  gender: '',
  weight: 0,
  height: 0,
  dietPurpose: '',
  physicalActivity: '',
  BMI: 0,
  caloricDemand: 0,
  proteinsDemand: 0,
  fatsDemand: 0,
  carbohydratesDemand: 0,
  recipes: [],
};
